cake-build/bakery

src/Cake.Bakery/Configuration/CakeConfiguration.cs, src/Cake.Bakery/Constants.cs, src/Cake.Bakery/Diagnostics/ConsoleLogger.cs, src/Cake.Bakery/Packaging/DefaultPackageInstaller.cs, src/Cake.Bakery/Program.cs, src/Cake.Scripting.Core/CodeGen/CakeScript.cs, src/Cake.Scripting.Core/CodeGen/CakeScriptAliasGenerator.cs, src/Cake.Scripting.Core/CodeGen/CakeScriptGenerator.cs, src/Cake.Scripting.Core/Constants.cs
=> [WIP] ScriptGen implementation

src/Cake.Bakery.IntegrationTests/IntegrationFixture.cs, src/Cake.Bakery.IntegrationTests/IntegrationTests.cs, src/Cake.Bakery/Program.cs, src/Cake.Scripting.Tests/Cake.Scripting.Tests.csproj, src/Cake.Scripting.Tests/Extensions/FileSystemExtensions.cs, src/Cake.Scripting.Tests/Fixtures/BufferedFileSystemFixture.cs, src/Cake.Scripting.Tests/Unit/IO/BufferedFileSystemTests.cs, src/Cake.Scripting/CodeGen/CakeScriptGenerator.cs, src/Cake.Scripting/IO/BufferedFile.cs, src/Cake.Scripting/IO/BufferedFileSystem.cs, src/Cake.Scripting/IO/IBufferedFileSystem.cs
To handle buffer changes to cake files
This PR is based on #9 will rebase once it's merged
=> Bufferered file system

src/Cake.Bakery/BakeryModule.cs, src/Cake.Bakery/Program.cs, src/Cake.Scripting/ScriptingModule.cs
=> GH-24: Add modules for Bakery and Scripting

src/Cake.Bakery.IntegrationTests/IntegrationFixture.cs, src/Cake.Bakery.IntegrationTests/IntegrationTests.cs, src/Cake.Bakery/Program.cs, src/Cake.Scripting.Transport/Extensions/SocketExtensions.cs, src/Cake.Scripting.Transport/Tcp/Client/ScriptGenerationClient.cs, src/Cake.Scripting.Transport/Tcp/Client/ScriptGenerationProcess.cs, src/Cake.Scripting.Transport/Tcp/Server/ScriptGenerationServer.cs
=> (GH-21) Better shutdown handling

README.md
=> (doc) Added AppVeyor Build information

src/Cake.Scripting.Abstractions/Models/CakeScript.cs, src/Cake.Scripting.Abstractions/Models/ScriptHost.cs, src/Cake.Scripting.Transport/Serialization/CakeScriptSerializer.cs, src/Cake.Scripting/CodeGen/CakeScriptGenerator.cs
=> GH-34: Return information about script host

src/Cake.Scripting.Tests/Cake.Scripting.Tests.csproj, src/Cake.Scripting.Tests/Data/CakeMethodAliasGeneratorData.cs, src/Cake.Scripting.Tests/Data/Expected/Methods/Generic_ExtensionMethodWithGenericOutParameter, src/Cake.Scripting.Tests/Data/Expected/Methods/NonGeneric_ExtensionMethodWithGenericOutParameter, src/Cake.Scripting.Tests/Unit/CodeGen/CakeMethodAliasGeneratorTests.cs, src/Cake.Scripting/Reflection/TypeSignature.cs
=> GH-42: Handle ByReference parameters

src/Cake.Scripting.Tests/Data/CakeMethodAliasGeneratorData.cs, src/Cake.Scripting.Tests/Unit/CodeGen/CakeScriptAliasFinderTests.cs, src/Cake.Scripting/CodeGen/CakeScriptAliasFinder.cs, src/Cake.Scripting/Extensions/TypeDefinitionExtensions.cs
=> GH44: Fixed namespace imports for aliases.

src/Cake.Bakery/CacheModule.cs, src/Cake.Bakery/Program.cs, src/Cake.Bakery/Scripting/CachingScriptAliasFinder.cs, src/Cake.Scripting.Tests/Fixtures/CakeAliasGeneratorFixture.cs, src/Cake.Scripting.Tests/Unit/CodeGen/CakeScriptAliasFinderTests.cs, src/Cake.Scripting/CodeGen/CakeScriptAliasFinder.cs, src/Cake.Scripting/CodeGen/CakeScriptAliasGenerator.cs, src/Cake.Scripting/CodeGen/CakeScriptGenerator.cs, src/Cake.Scripting/CodeGen/IScriptAliasFinder.cs, src/Cake.Scripting/ScriptingModule.cs
Fixes #11
ping @patriksvensson
=> GH11: Cache generated aliases

build.ps1, tests/integration/Cake.Bakery.IntegrationTests/Data/build.ps1
@mholo65 can you please review?
=> (maint) Switching to use https

src/Cake.Scripting.Transport/Tcp/Server/ScriptGenerationServer.cs
=> (GH-58) Handle all exceptions in server

setup.cake, src/Cake.Scripting.Tests/Cake.Scripting.Tests.csproj, src/Cake.Scripting.Tests/Data/CakeMethodAliasGeneratorData.cs, src/Cake.Scripting.Tests/Data/Expected/Methods/Generic_ExtensionMethodWithGenericReturnValueAndTypeParamConstraints, src/Cake.Scripting.Tests/Unit/CodeGen/CakeMethodAliasGeneratorTests.cs, src/Cake.Scripting/CodeGen/Generators/CakeMethodAliasGenerator.cs, src/Cake.Scripting/Reflection/GenericParameterSignature.cs, src/Cake.Scripting/Reflection/MethodSignature.cs
=> GH52: Add support for generic constraints

setup.cake, signclient.filter, signclient.json
=> GH51: Sign binaries before publishing.

src/Cake.Bakery/CacheModule.cs, src/Cake.Bakery/Cake.Bakery.csproj, src/Cake.Bakery/Program.cs, src/Cake.Bakery/Scripting/CachingScriptProcessor.cs, src/Cake.Bakery/Scripting/PackageReferenceComparer.cs, tests/integration/addin.cake, tests/integration/tests.cake
=> GH54: Enhance addin installation

src/Cake.Scripting/CodeGen/CakeScriptGenerator.cs
=> GH87: Check if reference exists before trying to find aliases-

src/Cake.Bakery/Cake.Bakery.csproj, src/Cake.Bakery/Scripting/CachingScriptProcessor.cs, src/Cake.Scripting.Tests/Cake.Scripting.Tests.csproj, src/Cake.Scripting/Cake.Scripting.csproj
=> GH89: Update to Cake 0.24.0-alpha

setup.cake, signclient.filter
- Fixes #91 
@gep13 do I need to take any further actions in order to get artifact uploaded to appveyor AND to github release?
=> GH91: Create ZIP artifact.

src/Cake.Bakery/Cake.Bakery.csproj, src/Cake.Scripting.Tests/Cake.Scripting.Tests.csproj, src/Cake.Scripting/Cake.Scripting.csproj
=> (GH-97) Update to Cake 0.26.0

src/Cake.Bakery/Cake.Bakery.csproj, src/Cake.Scripting.Tests/Cake.Scripting.Tests.csproj, src/Cake.Scripting/Cake.Scripting.csproj, tests/integration/tests.cake, tools/packages.config
=> (GH-102) Update to Cake 0.27.0

src/Cake.Scripting/CodeGen/CakeScriptGenerator.cs
to the search path for Cake.
Also, restructured the search order:
* cake.exe in /tools/
* dotnet-cake[.exe] in %HOME%/.dotnet/tools
* dotnet-cake[.exe] in %PATH%
* cake.exe in %PATH%
fixes #125
=> (GH-125) added %HOME/.dotnet/tools

src/Cake.Scripting/CodeGen/CakeScriptGenerator.cs
=> Make sure a reference to System.Linq is present.

src/Cake.Scripting/CodeGen/CakeScriptGenerator.cs
=> GH148: Use Cake Scripting Conventions

src/Cake.Scripting/Cake.Scripting.csproj, src/Cake.Scripting/CodeGen/CakeScriptGenerator.cs, src/Cake.Scripting/Polyfill/IReferenceAssemblyResolver.cs, src/Cake.Scripting/Reflection/ReferenceAssemblyResolver.cs, src/Cake.Scripting/ScriptingModule.cs
* fixes #148
Makes i.e. System.Tasks.Parallel work in all scenarios and many more assemblies.
=> GH148: Also use Basic.Reference.Assemblies

src/Cake.Scripting/Reflection/ReferenceAssemblyResolver.cs
=> GH152: Load Reference Assemblies References too

src/Cake.Bakery/Cake.Bakery.csproj, src/Shared.props
=> GH154: Add Cake XMLDOC during publish

recipe.cake, src/Cake.Bakery.Tests/Cake.Bakery.Tests.csproj, src/Cake.Bakery/Cake.Bakery.csproj, src/Cake.Scripting.Tests/Cake.Scripting.Tests.csproj, src/Cake.Scripting.Transport.Tests/Cake.Scripting.Transport.Tests.csproj, src/Cake.Scripting.Transport/Cake.Scripting.Transport.csproj, src/Cake.Scripting/Cake.Scripting.csproj, src/Cake.Scripting/Reflection/GenericParameterSignature.cs, tests/integration/Cake.Bakery.Tests.Integration.csproj, tests/integration/Program.cs
* Update Cake.* to 2.0.0-rc0001
* Update Mono.Cecil to 0.11.4
* Update Microsoft.Extensions.Logging to 6.0.0
* Update xunit.runner.visualstudio yo 2.4.3
* Update Xunit.Assert to 2.4.1
* Update xunit to 2.4.1
* Add #tool NuGet.CommandLine 5.11.0
* Update Microsoft.NET.Test.Sdk to 17.0.0
=> Update bakery to Cake 2.0.0-rc0001

src/Cake.Bakery/Cake.Bakery.csproj, src/Cake.Scripting.Tests/Cake.Scripting.Tests.csproj, src/Cake.Scripting/Cake.Scripting.csproj
=> GH161: Update to Cake 2.0

src/Cake.Scripting/CodeGen/CakeScriptGenerator.cs
=> GH166: Don't add non cil script references

src/Cake.Bakery/Cake.Bakery.csproj, src/Cake.Scripting.Tests/Cake.Scripting.Tests.csproj, src/Cake.Scripting/Cake.Scripting.csproj
=> GH170: Update to Cake 2.1.0

src/Cake.Bakery/Cake.Bakery.csproj, src/Cake.Scripting.Tests/Cake.Scripting.Tests.csproj, src/Cake.Scripting/Cake.Scripting.csproj
=> GH172: Updated Cake tool to version 2.2.0

.appveyor.yml, .github/workflows/build.yml, global.json, recipe.cake, src/Cake.Bakery.Tests/Cake.Bakery.Tests.csproj, src/Cake.Bakery/Cake.Bakery.csproj, src/Cake.Scripting.Abstractions/Cake.Scripting.Abstractions.csproj, src/Cake.Scripting.Tests/Cake.Scripting.Tests.csproj, src/Cake.Scripting.Transport.Tests/Cake.Scripting.Transport.Tests.csproj, src/Cake.Scripting.Transport/Cake.Scripting.Transport.csproj, src/Cake.Scripting/Cake.Scripting.csproj, src/Cake.Scripting/Reflection/ReferenceAssemblyResolver.cs, tests/integration/Cake.Bakery.Tests.Integration.csproj
=> GH176: Updated Cake tool to version 3.0.0

.github/workflows/build.yml, .github/workflows/posixbuild.yml, global.json, src/Cake.Bakery.Tests/Cake.Bakery.Tests.csproj, src/Cake.Bakery/Cake.Bakery.csproj, src/Cake.Scripting.Tests/Cake.Scripting.Tests.csproj, src/Cake.Scripting.Transport.Tests/Cake.Scripting.Transport.Tests.csproj, src/Cake.Scripting/Cake.Scripting.csproj, tests/integration/Cake.Bakery.Tests.Integration.csproj
=> GH178: Updated Cake Tool to version 3.1.0
